/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary-fixed": "#23005c",
        "surface-container-highest": "#37333d",
        "surface-container": "#211e27",
        tertiary: "#ffb869",
        secondary: "#b7c8e1",
        "primary-fixed-dim": "#d0bcff",
        "on-surface": "#e7e0ed",
        "surface-container-low": "#1d1a23",
        "secondary-fixed": "#d3e4fe",
        "secondary-fixed-dim": "#b7c8e1",
        primary: "#d0bcff",
        "on-secondary-fixed-variant": "#38485d",
        "on-tertiary-fixed": "#2c1700",
        "on-primary": "#3c0091",
        "on-secondary-container": "#a9bad3",
        background: "#15121b",
        "on-surface-variant": "#cbc3d7",
        "on-tertiary-fixed-variant": "#673d00",
        "surface-variant": "#37333d",
        "tertiary-fixed": "#ffdcbb",
        "primary-fixed": "#e9ddff",
        "on-error": "#690005",
        "surface-tint": "#d0bcff",
        "inverse-primary": "#6d3bd7",
        "on-background": "#e7e0ed",
        "on-secondary": "#213145",
        "inverse-surface": "#e7e0ed",
        "inverse-on-surface": "#322f39",
        "on-tertiary-container": "#3f2300",
        "error-container": "#93000a",
        surface: "#15121b",
        "on-primary-fixed-variant": "#5516be",
        "surface-bright": "#3b3742",
        "on-tertiary": "#482900",
        "tertiary-fixed-dim": "#ffb869",
        outline: "#958ea0",
        "surface-container-lowest": "#0f0d15",
        "primary-container": "#a078ff",
        "secondary-container": "#3a4a5f",
        "on-error-container": "#ffdad6",
        "surface-container-high": "#2c2832",
        "surface-dim": "#15121b",
        "tertiary-container": "#ca801e",
        "on-secondary-fixed": "#0b1c30",
        "outline-variant": "#494454",
        error: "#ffb4ab",
        "on-primary-container": "#340080",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        gutter: "24px",
        "sidebar-width": "320px",
        "chat-max-width": "800px",
        base: "8px",
        "container-padding-mobile": "16px",
        "container-padding-desktop": "32px",
      },
      fontFamily: {
        "headline-md": ["Inter"],
        display: ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "headline-lg": ["Inter"],
        "label-md": ["JetBrains Mono"],
        "body-lg": ["Inter"],
        "body-md": ["Inter"],
        "label-sm": ["JetBrains Mono"],
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
}
